-- =====================================================================
--  NHP iPad Management System — Database Schema (PostgreSQL / Supabase)
--  โรงเรียนหนองหงส์พิทยาคม สังกัด สพม.บุรีรัมย์
--
--  วิธีใช้:  เปิด Supabase Dashboard -> SQL Editor -> วางไฟล์นี้ทั้งหมด -> Run
--  PK ใช้ bigint identity (รองรับ id ที่แอปสร้างจาก Date.now()) และ
--  เก็บฟิลด์ครบตามที่หน้าจอใช้งาน เพื่อให้ "เพิ่ม/แก้ไข" บันทึกแล้วกลับมาครบ
-- =====================================================================

-- ---------- ปีการศึกษา ----------
create table academic_years (
  id          bigint generated by default as identity primary key,
  year        text not null,
  is_current  boolean not null default false,
  created_at  timestamptz not null default now()
);

-- ---------- การตั้งค่าระบบ (singleton แถวเดียว) ----------
create table settings (
  id            int primary key default 1,
  school_name   text not null default 'โรงเรียนหนองหงส์พิทยาคม',
  affiliation   text default 'สพม.บุรีรัมย์',
  address       text,
  logo_url      text,
  current_year  text default '2569',
  current_term  text default '1',
  backup_freq   text default 'ทุกวัน เวลา 02:00 น.',
  updated_at    timestamptz not null default now(),
  constraint settings_single_row check (id = 1)
);

-- ---------- วิชา ----------
create table subjects (
  id    bigint generated by default as identity primary key,
  name  text not null unique
);

-- ---------- บุคลากรครู ----------
create table teachers (
  id           bigint generated by default as identity primary key,
  code         text,                          -- T001
  prefix       text,                          -- นาย/นาง/นางสาว
  first_name   text not null,
  last_name    text not null,
  sex          text,
  subject      text,                          -- ชื่อวิชา (เก็บเป็นข้อความเพื่อให้แก้ไขง่าย)
  role         text,                          -- ครูผู้สอน/หัวหน้างาน ฯลฯ
  homeroom     text,                          -- ครูประจำชั้น เช่น "ม.1/2"
  email        text,
  phone        text,
  photo_url    text,
  status       text not null default 'ปฏิบัติงาน',
  created_at   timestamptz not null default now()
);

-- ---------- นักเรียน ----------
create table students (
  id           bigint generated by default as identity primary key,
  student_code text,                          -- รหัสนักเรียน
  citizen      text,                          -- เลขประจำตัวประชาชน
  prefix       text,                          -- เด็กชาย/เด็กหญิง/นาย/นางสาว
  first_name   text not null,
  last_name    text not null,
  sex          text,
  level        text not null,                 -- ม.1 .. ม.6
  room         int not null,
  no           int,                           -- เลขที่
  phone        text,
  parent       text,                          -- ชื่อผู้ปกครอง
  parent_phone text,
  photo_url    text,
  graduated    boolean not null default false,
  status       text not null default 'กำลังศึกษา',
  academic_year text,
  created_at   timestamptz not null default now()
);
create index idx_students_level_room on students(level, room);

-- ---------- ประเภทอุปกรณ์ ----------
create table device_types (
  id    text primary key,                     -- ipad / notebook / chromebook / projector / camera
  name  text not null,
  icon  text
);

-- ---------- อุปกรณ์ (ครุภัณฑ์) ----------
create table devices (
  id           bigint generated by default as identity primary key,
  asset_tag    text not null unique,          -- NHP-IPD-001
  inv_code     text,                          -- เลขครุภัณฑ์
  type         text not null references device_types(id),
  type_name    text,
  brand        text,
  model        text,
  color        text,
  capacity     text,                           -- ความจุ เช่น 128GB
  serial       text,
  budget_year  int,                            -- ปีงบประมาณ
  price        numeric(12,2),
  received_date text,
  status       text not null default 'พร้อมใช้งาน',
  status_cls   text,
  holder       text,
  holder_level text,
  note         text,
  created_at   timestamptz not null default now()
);
create index idx_devices_status on devices(status);
create index idx_devices_type on devices(type);

-- ---------- อุปกรณ์เสริม (คลังรวม) ----------
create table accessories (
  id        bigint generated by default as identity primary key,
  name      text not null,
  qty       int not null default 0,           -- คงเหลือพร้อมจ่าย
  damaged   int not null default 0,
  lost      int not null default 0,
  note      text
);

-- ---------- รายการยืม ----------
create table borrows (
  id            bigint generated by default as identity primary key,
  device_id     bigint references devices(id),
  asset_tag     text,
  borrower_kind text check (borrower_kind in ('s','t')),
  borrower_id   bigint,
  holder_name   text,
  level         text,
  academic_year text,
  term          text,
  borrow_date   text,
  due_date      text,
  status        text default 'ปกติ',
  note          text,
  created_at    timestamptz not null default now()
);
create index idx_borrows_device on borrows(device_id);

-- ---------- ใบแจ้งซ่อม iPad ----------
create table repairs (
  id           bigint generated by default as identity primary key,
  ticket       text,
  device_id    bigint references devices(id),
  asset_tag    text,
  model        text,
  type         text,
  status       text default 'รอดำเนินการ',
  status_cls   text,
  reporter     text,
  report_date  text,
  note         text,
  created_at   timestamptz not null default now()
);

-- ---------- ประเภทปัญหาการซ่อม ----------
create table repair_types (
  id     bigint generated by default as identity primary key,
  scope  text not null default 'device',      -- device / accessory
  name   text not null
);

-- ---------- ผู้ใช้ระบบ / RBAC (ผูกกับ auth.users) ----------
create table app_users (
  id         uuid primary key references auth.users(id) on delete cascade,
  name       text,
  username   text unique,
  email      text,
  role       text not null default 'ครู',      -- Super Admin / Admin / ICT / ครู / นักเรียน
  active     boolean not null default true,
  twofa      boolean not null default false,
  last_login timestamptz,
  created_at timestamptz not null default now()
);

-- ---------- Audit Log ----------
create table audit_log (
  id        bigserial primary key,
  action    text not null,
  detail    text,
  cls       text default 'b-info',
  actor     text,
  actor_id  uuid references app_users(id) on delete set null,
  nav       text,
  ip        text,
  at        timestamptz not null default now()
);
create index idx_audit_at on audit_log(at desc);

-- =====================================================================
--  Helper functions สำหรับ RLS
-- =====================================================================
create or replace function current_role_name()
returns text language sql stable security definer set search_path = public as $$
  select role from app_users where id = auth.uid()
$$;

create or replace function is_staff()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce(current_role_name() in ('Super Admin','Admin / ICT'), false)
$$;

-- =====================================================================
--  Row Level Security: login แล้วอ่านได้ทุกคน, แก้ไขเฉพาะ staff
-- =====================================================================
do $$
declare t text;
begin
  foreach t in array array[
    'academic_years','settings','subjects','teachers','students','device_types',
    'devices','accessories','borrows','repairs','repair_types','app_users','audit_log'
  ] loop
    execute format('alter table %I enable row level security;', t);
    execute format($f$create policy "read_authenticated" on %I for select to authenticated using (true);$f$, t);
    execute format($f$create policy "write_staff_ins" on %I for insert to authenticated with check (is_staff());$f$, t);
    execute format($f$create policy "write_staff_upd" on %I for update to authenticated using (is_staff());$f$, t);
    execute format($f$create policy "write_staff_del" on %I for delete to authenticated using (is_staff());$f$, t);
  end loop;
end $$;

create policy "self_read"  on app_users for select to authenticated using (id = auth.uid());
create policy "self_update" on app_users for update to authenticated using (id = auth.uid());

-- =====================================================================
--  Trigger: สร้าง app_users อัตโนมัติเมื่อมีผู้สมัครใหม่
-- =====================================================================
create or replace function handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into app_users (id, email, name, username)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'name', new.email), split_part(new.email,'@',1))
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();
